services:
  mysql:
    image: mysql:8
    container_name: mysql
    networks:
      - trance
    env_file:
      - mysql/.env
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - trance
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    build: mc-backend
    image: mcb:1.0
    container_name: mcb
    networks:
      - trance
    ports:
      - 3000:3000
    volumes:
      - ./mc-backend/app:/app
      - /app/node_modules
    env_file:
      - mc-backend/app/.env
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

  front:
    build: mc-frontend
    image: mcf:1.0
    container_name: mcf
    networks:
      - trance
    ports:
      - 5173:5173
    volumes:
      - ./mc-frontend/app:/app
      - /app/node_modules
    restart: on-failure
    depends_on:
      - back

networks:
  trance:
    name: trance
    driver: bridge
